---
- name: Check if Docker is running in Swarm mode
  command: docker node ls
  register: docker_node_ls_result  
  ignore_errors: yes
  changed_when: False
  
- name: Initialize new swarm
  command: docker swarm init --advertise-addr=127.0.0.1
  when: docker_node_ls_result.rc != 0

