---
- name: Ensure that Docker configuration directory exists
  file: 
    path: /etc/docker
    state: directory
    
- name: Copy Docker config to allow insecure registry
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    
- name: Install necessary packages for Docker
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - python-docker

- name: Add key for docker apt repository
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install Docker
  apt:
    update_cache: yes
    name: docker-ce
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    enabled: true
    state: started

- name: Ensure that Docker can run an image (step 1)
  command: docker run --rm busybox echo Hello world
  register: docker_test_output

- name: Ensure that Docker can run an image (step 2)
  assert:
    that: 'docker_test_output.stdout == "Hello world"'

